import spikeinterface as si
import spikeinterface.extractors as se
import numpy as np
import matplotlib.pyplot as plt
import os
from ipywidgets import interact, IntSlider
import ipywidgets as widgets

data = {
    "Behavioural": {
        "Aquisition": {
            "Extracted Behaviours": {
                "Darting" : {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Behavioural Data\Extracted Behaviours\Darting",
                },
                "Freezing": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Behavioural Data\Extracted Behaviours\Freezing",
                },
                "Grooming": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Behavioural Data\Extracted Behaviours\Grooming",
                },
                "Position": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Behavioural Data\Extracted Behaviours\Position",
                },
                "Rearing": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Behavioural Data\Extracted Behaviours\Rearing",
                },
                "Velocity": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Behavioural Data\Extracted Behaviours\Velocity",
                },
            },
            "Raw DLC Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Behavioural Data\Raw DLC Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Behavioural Data\Raw DLC Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Behavioural Data\Raw DLC Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Behavioural Data\Raw DLC Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Behavioural Data\Raw DLC Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Behavioural Data\Raw DLC Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Behavioural Data\Raw DLC Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Behavioural Data\Raw DLC Data",
            },
            "SMM fitted data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Behavioural Data\SSM Fitted Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Behavioural Data\SSM Fitted Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Behavioural Data\SSM Fitted Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Behavioural Data\SSM Fitted Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Behavioural Data\SSM Fitted Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Behavioural Data\SSM Fitted Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Behavioural Data\SSM Fitted Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Behavioural Data\SSM Fitted Data",
            },
            "Traingulated Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Behavioural Data\Triangulated Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Behavioural Data\Triangulated Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Behavioural Data\Triangulated Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Behavioural Data\Triangulated Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Behavioural Data\Triangulated Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Behavioural Data\Triangulated Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Behavioural Data\Triangulated Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Behavioural Data\Triangulated Data",
            },
            "Video Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Behavioural Data\Video Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Behavioural Data\Video Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Behavioural Data\Video Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Behavioural Data\Video Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Behavioural Data\Video Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Behavioural Data\Video Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Behavioural Data\Video Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Behavioural Data\Video Data",
            },
        },
        "Extinction": {
            "Extracted Behaviours": {
                "Darting" : {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Behavioural Data\Extracted Behaviours\Darting",
                },
                "Freezing": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Behavioural Data\Extracted Behaviours\Freezing",
                },
                "Grooming": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Behavioural Data\Extracted Behaviours\Grooming",
                },
                "Position": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Behavioural Data\Extracted Behaviours\Position",
                },
                "Rearing": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Behavioural Data\Extracted Behaviours\Rearing",
                },
                "Velocity": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Behavioural Data\Extracted Behaviours\Velocity",
                },
            },
            "Raw DLC Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Behavioural Data\Raw DLC Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Behavioural Data\Raw DLC Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Behavioural Data\Raw DLC Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Behavioural Data\Raw DLC Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Behavioural Data\Raw DLC Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Behavioural Data\Raw DLC Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Behavioural Data\Raw DLC Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Behavioural Data\Raw DLC Data",
            },
            "SMM fitted data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Behavioural Data\SSM Fitted Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Behavioural Data\SSM Fitted Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Behavioural Data\SSM Fitted Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Behavioural Data\SSM Fitted Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Behavioural Data\SSM Fitted Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Behavioural Data\SSM Fitted Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Behavioural Data\SSM Fitted Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Behavioural Data\SSM Fitted Data",
            },
            "Traingulated Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Behavioural Data\Triangulated Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Behavioural Data\Triangulated Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Behavioural Data\Triangulated Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Behavioural Data\Triangulated Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Behavioural Data\Triangulated Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Behavioural Data\Triangulated Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Behavioural Data\Triangulated Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Behavioural Data\Triangulated Data",
            },
            "Video Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Behavioural Data\Video Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Behavioural Data\Video Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Behavioural Data\Video Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Behavioural Data\Video Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Behavioural Data\Video Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Behavioural Data\Video Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Behavioural Data\Video Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Behavioural Data\Video Data",
            },
        
        },
        "Renewal": {
            "Extracted Behaviours": {
                "Darting" : {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Behavioural Data\Extracted Behaviours\Darting",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Behavioural Data\Extracted Behaviours\Darting",
                },
                "Freezing": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Behavioural Data\Extracted Behaviours\Freezing",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Behavioural Data\Extracted Behaviours\Freezing",
                },
                "Grooming": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Behavioural Data\Extracted Behaviours\Grooming",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Behavioural Data\Extracted Behaviours\Grooming",
                },
                "Position": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Behavioural Data\Extracted Behaviours\Position",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Behavioural Data\Extracted Behaviours\Position",
                },
                "Rearing": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Behavioural Data\Extracted Behaviours\Rearing",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Behavioural Data\Extracted Behaviours\Rearing",
                },
                "Velocity": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Behavioural Data\Extracted Behaviours\Velocity",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Behavioural Data\Extracted Behaviours\Velocity",
                },
            },
            "Raw DLC Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Behavioural Data\Raw DLC Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Behavioural Data\Raw DLC Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Behavioural Data\Raw DLC Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Behavioural Data\Raw DLC Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Behavioural Data\Raw DLC Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Behavioural Data\Raw DLC Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Behavioural Data\Raw DLC Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Behavioural Data\Raw DLC Data",
            },
            "SMM fitted data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Behavioural Data\SSM Fitted Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Behavioural Data\SSM Fitted Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Behavioural Data\SSM Fitted Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Behavioural Data\SSM Fitted Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Behavioural Data\SSM Fitted Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Behavioural Data\SSM Fitted Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Behavioural Data\SSM Fitted Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Behavioural Data\SSM Fitted Data",
            },
            "Traingulated Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Behavioural Data\Triangulated Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Behavioural Data\Triangulated Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Behavioural Data\Triangulated Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Behavioural Data\Triangulated Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Behavioural Data\Triangulated Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Behavioural Data\Triangulated Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Behavioural Data\Triangulated Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Behavioural Data\Triangulated Data",
            },
            "Video Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Behavioural Data\Video Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Behavioural Data\Video Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Behavioural Data\Video Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Behavioural Data\Video Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Behavioural Data\Video Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Behavioural Data\Video Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Behavioural Data\Video Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Behavioural Data\Video Data",
            },
        
        },
    },
    "Combined": {
        "Aquisition": {
            "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Combined Data",
            "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Combined Data",
            "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Combined Data",
            "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Combined Data",
            "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Combined Data",
            "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Combined Data",
            "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Combined Data",
            "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Combined Data",
        },
        "Extinction": {
            "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Combined Data",
            "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Combined Data",
            "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Combined Data",
            "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Combined Data",
            "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Combined Data",
            "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Combined Data",
            "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Combined Data",
            "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Combined Data",
        },
        "Renewal": {
            "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Combined Data",
            "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Combined Data",
            "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Combined Data",
            "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Combined Data",
            "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Combined Data",
            "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Combined Data",
            "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Combined Data",
            "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Combined Data",
        },
    },
    "Neural": {
        "Aquisition": {
            "Concatenated Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Neural Data\Concatenated Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Neural Data\Concatenated Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Neural Data\Concatenated Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Neural Data\Concatenated Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Neural Data\Concatenated Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Neural Data\Concatenated Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Neural Data\Concatenated Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Neural Data\Concatenated Data",
                "kilosort4": {
                    "Mouse 2": r"",
                    "Mouse 3": r"",
                    "Mouse 4": r"",
                    "Mouse 5": r"",
                    "Mouse 6": r"",
                    "Mouse 7": r"",
                    "Mouse 8": r"",
                    "Mouse 9": r"",
                },
            },
            "Raw Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Neural Data\Raw Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Neural Data\Raw Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Neural Data\Raw Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Neural Data\Raw Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Neural Data\Raw Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Neural Data\Raw Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Neural Data\Raw Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Neural Data\Raw Data",
            },
            "Triggers": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Acquisition\Neural Data\Triggers",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Acquisition\Neural Data\Triggers",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Acquisition\Neural Data\Triggers",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Acquisition\Neural Data\Triggers",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Acquisition\Neural Data\Triggers",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Acquisition\Neural Data\Triggers",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Acquisition\Neural Data\Triggers",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Acquisition\Neural Data\Triggers",
            },
        },
        "Extinction": {
            "Concatenated Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Neural Data\Concatenated Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Neural Data\Concatenated Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Neural Data\Concatenated Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Neural Data\Concatenated Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Neural Data\Concatenated Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Neural Data\Concatenated Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Neural Data\Concatenated Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Neural Data\Concatenated Data",
                "kilosort4": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Neural Data\Concatenated Data\kilosort4",
                },
            },
            "Raw Data": {
                "Habituation": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Neural Data\Raw Data\mouse2_extinction_habituation_2025-06-06_13-13-19",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Neural Data\Raw Data\mouse3_extinction_habituation",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Neural Data\Raw Data\mouse4_extinction_habituation",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Neural Data\Raw Data\mouse5_extinction_habituation",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Neural Data\Raw Data\mouse6_extinction_habituation",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Neural Data\Raw Data\mouse7_extinction_habituation",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Neural Data\Raw Data\mouse8_extinction_habituation",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Neural Data\Raw Data\mouse9_extinction_habituation",
                },
                "part 1": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Neural Data\Raw Data\mouse2_extinction_p1_2025-06-06_13-24-00",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Neural Data\Raw Data\mouse3_extinction_p1",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Neural Data\Raw Data\mouse4_extinction_p1",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Neural Data\Raw Data\mouse5_extinction_p1",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Neural Data\Raw Data\mouse6_extinction_p1",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Neural Data\Raw Data\mouse7_extinction_p1",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Neural Data\Raw Data\mouse8_extinction_p1",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Neural Data\Raw Data\mouse9_extinction_p1",
                },
                "part 2": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Neural Data\Raw Data\mouse2_extinction_p2_2025-06-06_13-48-21",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Neural Data\Raw Data\mouse3_extinction_p2",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Neural Data\Raw Data\mouse4_extinction_p2",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Neural Data\Raw Data\mouse5_extinction_p2",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Neural Data\Raw Data\mouse6_extinction_p2",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Neural Data\Raw Data\mouse7_extinction_p2",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Neural Data\Raw Data\mouse8_extinction_p2",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Neural Data\Raw Data\mouse9_extinction_p2",
                },
            },
            "Triggers": {
                "Extracted events": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Neural Data\Triggers\mouse 2_extinction_extracted_events.mat",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Neural Data\Triggers\mouse 3_extinction_extracted_events.mat",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Neural Data\Triggers\mouse 4_extinction_extracted_events.mat",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Neural Data\Triggers\mouse 5_extinction_extracted_events.mat",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Neural Data\Triggers\mouse 6_extinction_extracted_events.mat",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Neural Data\Triggers\mouse 7_extinction_extracted_events.mat",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Neural Data\Triggers\mouse 8_extinction_extracted_events.mat",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Neural Data\Triggers\mouse 9_extinction_extracted_events.mat",
                },
                "Habituation": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Neural Data\Triggers\mouse2_extinction_habituation_triggers.mat",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Neural Data\Triggers\mouse3_extinction_habituation_triggers.mat",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Neural Data\Triggers\mouse4_extinction_habituation_triggers.mat",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Neural Data\Triggers\mouse5_extinction_habituation_triggers.mat",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Neural Data\Triggers\mouse6_extinction_habituation_triggers.mat",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Neural Data\Triggers\mouse7_extinction_habituation_triggers.mat",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Neural Data\Triggers\mouse8_extinction_habituation_triggers.mat",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Neural Data\Triggers\mouse9_extinction_habituation_triggers.mat",
                },
                "part 1": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Neural Data\Triggers\mouse2_extinction_p1_triggers.mat",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Neural Data\Triggers\mouse3_extinction_p1_triggers.mat",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Neural Data\Triggers\mouse4_extinction_p1_triggers.mat",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Neural Data\Triggers\mouse5_extinction_p1_triggers.mat",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Neural Data\Triggers\mouse6_extinction_p1_triggers.mat",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Neural Data\Triggers\mouse7_extinction_p1_triggers.mat",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Neural Data\Triggers\mouse8_extinction_p1_triggers.mat",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Neural Data\Triggers\mouse9_extinction_p1_triggers.mat",
                },
                "part 2": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Extinction\Neural Data\Triggers\mouse2_extinction_p2_triggers.mat",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Extinction\Neural Data\Triggers\mouse3_extinction_p2_triggers.mat",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Extinction\Neural Data\Triggers\mouse4_extinction_p2_triggers.mat",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Extinction\Neural Data\Triggers\mouse5_extinction_p2_triggers.mat",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Extinction\Neural Data\Triggers\mouse6_extinction_p2_triggers.mat",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Extinction\Neural Data\Triggers\mouse7_extinction_p2_triggers.mat",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Extinction\Neural Data\Triggers\mouse8_extinction_p2_triggers.mat",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Extinction\Neural Data\Triggers\mouse9_extinction_p2_triggers.mat",
                },
            },
        },
        "Renewal": {
            "Concatenated Data": {
                "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Neural Data\Concatenated Data",
                "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Neural Data\Concatenated Data",
                "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Neural Data\Concatenated Data",
                "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Neural Data\Concatenated Data",
                "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Neural Data\Concatenated Data",
                "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Neural Data\Concatenated Data",
                "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Neural Data\Concatenated Data",
                "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Neural Data\Concatenated Data",
                "kilosort4": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Neural Data\Concatenated Data\kilosort4",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Neural Data\Concatenated Data\kilosort4",
                },
            },
            "Raw Data": {
                "Checkerboard": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Neural Data\Raw Data\mouse2_renewal_checkerboard_2025-06-12_12-52-28",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Neural Data\Raw Data\mouse3_renewal_checkerboard",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Neural Data\Raw Data\mouse4_renewal_checkerboard",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Neural Data\Raw Data\mouse5_renewal_checkerboard",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Neural Data\Raw Data\mouse6_renewal_checkerboard",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Neural Data\Raw Data\mouse7_renewal_checkerboard",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Neural Data\Raw Data\mouse8_renewal_checkerboard",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Neural Data\Raw Data\mouse9_renewal_checkerboard",
                },
                "Habituation": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Neural Data\Raw Data\mouse2_renewal_habituation_2025-06-12_11-56-40",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Neural Data\Raw Data\mouse3_renewal_habituation",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Neural Data\Raw Data\mouse4_renewal_habituation",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Neural Data\Raw Data\mouse5_renewal_habituation",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Neural Data\Raw Data\mouse6_renewal_habituation",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Neural Data\Raw Data\mouse7_renewal_habituation",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Neural Data\Raw Data\mouse8_renewal_habituation",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Neural Data\Raw Data\mouse9_renewal_habituation",
                },
                "part 1": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Neural Data\Raw Data\mouse2_renewal_p1_2025-06-12_12-04-58",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Neural Data\Raw Data\mouse3_renewal_p1",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Neural Data\Raw Data\mouse4_renewal_p1",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Neural Data\Raw Data\mouse5_renewal_p1",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Neural Data\Raw Data\mouse6_renewal_p1",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Neural Data\Raw Data\mouse7_renewal_p1",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Neural Data\Raw Data\mouse8_renewal_p1",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Neural Data\Raw Data\mouse9_renewal_p1",
                },
                "part 2": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Neural Data\Raw Data\mouse2_renewal_p2_2025-06-12_12-28-14",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Neural Data\Raw Data\mouse3_renewal_p2",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Neural Data\Raw Data\mouse4_renewal_p2",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Neural Data\Raw Data\mouse5_renewal_p2",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Neural Data\Raw Data\mouse6_renewal_p2",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Neural Data\Raw Data\mouse7_renewal_p2",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Neural Data\Raw Data\mouse8_renewal_p2",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Neural Data\Raw Data\mouse9_renewal_p2",
                },
            },
            "Triggers": {
                "Checkerboard": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Neural Data\Triggers\mouse2_renewal_checkerboard_triggers.mat",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Neural Data\Triggers\mouse3_renewal_checkerboard_triggers.mat",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Neural Data\Triggers\mouse4_renewal_checkerboard_triggers.mat",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Neural Data\Triggers\mouse5_renewal_checkerboard_triggers.mat",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Neural Data\Triggers\mouse6_renewal_checkerboard_triggers.mat",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Neural Data\Triggers\mouse7_renewal_checkerboard_triggers.mat",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Neural Data\Triggers\mouse8_renewal_checkerboard_triggers.mat",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Neural Data\Triggers\mouse9_renewal_checkerboard_triggers.mat",
                },
                "Extracted events": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Neural Data\Triggers\mouse 2_renewal_extracted_events.mat",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Neural Data\Triggers\mouse 3_renewal_extracted_events.mat",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Neural Data\Triggers\mouse 4_renewal_extracted_events.mat",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Neural Data\Triggers\mouse 5_renewal_extracted_events.mat",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Neural Data\Triggers\mouse 6_renewal_extracted_events.mat",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Neural Data\Triggers\mouse 7_renewal_extracted_events.mat",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Neural Data\Triggers\mouse 8_renewal_extracted_events.mat",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Neural Data\Triggers\mouse 9_renewal_extracted_events.mat",
                },
                "Habituation": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Neural Data\Triggers\mouse2_renewal_habituation_triggers.mat",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Neural Data\Triggers\mouse3_renewal_habituation_triggers.mat",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Neural Data\Triggers\mouse4_renewal_habituation_triggers.mat",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Neural Data\Triggers\mouse5_renewal_habituation_triggers.mat",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Neural Data\Triggers\mouse6_renewal_habituation_triggers.mat",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Neural Data\Triggers\mouse7_renewal_habituation_triggers.mat",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Neural Data\Triggers\mouse8_renewal_habituation_triggers.mat",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Neural Data\Triggers\mouse9_renewal_habituation_triggers.mat",
                },
                "part 1": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Neural Data\Triggers\mouse2_renewal_p1_triggers.mat",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Neural Data\Triggers\mouse3_renewal_p1_triggers.mat",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Neural Data\Triggers\mouse4_renewal_p1_triggers.mat",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Neural Data\Triggers\mouse5_renewal_p1_triggers.mat",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Neural Data\Triggers\mouse6_renewal_p1_triggers.mat",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Neural Data\Triggers\mouse7_renewal_p1_triggers.mat",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Neural Data\Triggers\mouse8_renewal_p1_triggers.mat",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Neural Data\Triggers\mouse9_renewal_p1_triggers.mat",
                },
                "part 2": {
                    "Mouse 2": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 2\Renewal\Neural Data\Triggers\mouse2_renewal_p2_triggers.mat",
                    "Mouse 3": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 3\Renewal\Neural Data\Triggers\mouse3_renewal_p2_triggers.mat",
                    "Mouse 4": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 4\Renewal\Neural Data\Triggers\mouse4_renewal_p2_triggers.mat",
                    "Mouse 5": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 5\Renewal\Neural Data\Triggers\mouse5_renewal_p2_triggers.mat",
                    "Mouse 6": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 6\Renewal\Neural Data\Triggers\mouse6_renewal_p2_triggers.mat",
                    "Mouse 7": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 7\Renewal\Neural Data\Triggers\mouse7_renewal_p2_triggers.mat",
                    "Mouse 8": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 8\Renewal\Neural Data\Triggers\mouse8_renewal_p2_triggers.mat",
                    "Mouse 9": r"Z:\Mike\Data\Psilocybin Fear Conditioning\Cohort 4_06_05_25 (SC PAG Implanted Animals)\Mouse 9\Renewal\Neural Data\Triggers\mouse9_renewal_p2_triggers.mat",
                },
            },
        },
    }
}

